// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_add_store from "./routes/api/add-store.ts";
import * as $api_events from "./routes/api/events.ts";
import * as $api_events_export from "./routes/api/events/export.ts";
import * as $api_remove_store from "./routes/api/remove-store.ts";
import * as $api_store_health from "./routes/api/store-health.ts";
import * as $api_store_topics from "./routes/api/store-topics.ts";
import * as $api_stores from "./routes/api/stores.ts";
import * as $api_stores_name_ from "./routes/api/stores/[name].ts";
import * as $api_test_connection from "./routes/api/test-connection.ts";
import * as $api_topic_stats from "./routes/api/topic-stats.ts";
import * as $api_users from "./routes/api/users.ts";
import * as $consumers from "./routes/consumers.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $events from "./routes/events.tsx";
import * as $events_index from "./routes/events/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $topics from "./routes/topics.tsx";
import * as $topics_stats from "./routes/topics/stats.tsx";
import * as $topics_stats_stats from "./routes/topics/stats/stats.tsx";
import * as $AddStore from "./islands/AddStore.tsx";
import * as $AddUser from "./islands/AddUser.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DashboardStores from "./islands/DashboardStores.tsx";
import * as $EventBrowser from "./islands/EventBrowser.tsx";
import * as $RemoveStore from "./islands/RemoveStore.tsx";
import * as $StoreList from "./islands/StoreList.tsx";
import * as $StoreTopics from "./islands/StoreTopics.tsx";
import * as $TestConnection from "./islands/TestConnection.tsx";
import * as $TopicConfig from "./islands/TopicConfig.tsx";
import * as $TopicStats from "./islands/TopicStats.tsx";
import * as $UpdatePassword from "./islands/UpdatePassword.tsx";
import * as $UserList from "./islands/UserList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/add-store.ts": $api_add_store,
    "./routes/api/events.ts": $api_events,
    "./routes/api/events/export.ts": $api_events_export,
    "./routes/api/remove-store.ts": $api_remove_store,
    "./routes/api/store-health.ts": $api_store_health,
    "./routes/api/store-topics.ts": $api_store_topics,
    "./routes/api/stores.ts": $api_stores,
    "./routes/api/stores/[name].ts": $api_stores_name_,
    "./routes/api/test-connection.ts": $api_test_connection,
    "./routes/api/topic-stats.ts": $api_topic_stats,
    "./routes/api/users.ts": $api_users,
    "./routes/consumers.tsx": $consumers,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/events.tsx": $events,
    "./routes/events/index.tsx": $events_index,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/settings.tsx": $settings,
    "./routes/topics.tsx": $topics,
    "./routes/topics/stats.tsx": $topics_stats,
    "./routes/topics/stats/stats.tsx": $topics_stats_stats,
  },
  islands: {
    "./islands/AddStore.tsx": $AddStore,
    "./islands/AddUser.tsx": $AddUser,
    "./islands/Counter.tsx": $Counter,
    "./islands/DashboardStores.tsx": $DashboardStores,
    "./islands/EventBrowser.tsx": $EventBrowser,
    "./islands/RemoveStore.tsx": $RemoveStore,
    "./islands/StoreList.tsx": $StoreList,
    "./islands/StoreTopics.tsx": $StoreTopics,
    "./islands/TestConnection.tsx": $TestConnection,
    "./islands/TopicConfig.tsx": $TopicConfig,
    "./islands/TopicStats.tsx": $TopicStats,
    "./islands/UpdatePassword.tsx": $UpdatePassword,
    "./islands/UserList.tsx": $UserList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
